WITH QUALIFYING AS (
    SELECT
        *
    FROM SESSION.QUALIFYING_RESULTS
    WHERE SESSION_CD IN (4)
),

SESSION_DAT AS (
    SELECT
        P.EVENT_CD,
        P.DRIVER_ID,
        P.TEAM_ID,
        ROUND(SUM(P.LAPTIME_FP1), 3) AS LAPTIME_FP1,
        ROUND(SUM(P.SECTOR1_TIME_FP1), 3) AS SECTOR1_TIME_FP1,
        ROUND(SUM(P.SECTOR2_TIME_FP1), 3) AS SECTOR2_TIME_FP1,
        ROUND(SUM(P.SECTOR3_TIME_FP1), 3) AS SECTOR3_TIME_FP1,
        ROUND(SUM(P.LAPTIME_FP2), 3) AS LAPTIME_FP2,
        ROUND(SUM(P.SECTOR1_TIME_FP2), 3) AS SECTOR1_TIME_FP2,
        ROUND(SUM(P.SECTOR2_TIME_FP2), 3) AS SECTOR2_TIME_FP2,
        ROUND(SUM(P.SECTOR3_TIME_FP2), 3) AS SECTOR3_TIME_FP2,
        ROUND(SUM(P.LAPTIME_FP3), 3) AS LAPTIME_FP3,
        ROUND(SUM(P.SECTOR1_TIME_FP3), 3) AS SECTOR1_TIME_FP3,
        ROUND(SUM(P.SECTOR2_TIME_FP3), 3) AS SECTOR2_TIME_FP3,
        ROUND(SUM(P.SECTOR3_TIME_FP3), 3) AS SECTOR3_TIME_FP3
    FROM (
        SELECT
            P.EVENT_CD,
            P.DRIVER_ID,
            P.TEAM_ID,
            -- FP1
            CASE WHEN P.SESSION_CD IN (1) THEN P.LAPTIME END AS LAPTIME_FP1,
            CASE WHEN P.SESSION_CD IN (1) THEN P.SECTOR1_TIME END AS SECTOR1_TIME_FP1,
            CASE WHEN P.SESSION_CD IN (1) THEN P.SECTOR2_TIME END AS SECTOR2_TIME_FP1,
            CASE WHEN P.SESSION_CD IN (1) THEN P.SECTOR3_TIME END AS SECTOR3_TIME_FP1,
            -- FP2
            CASE WHEN P.SESSION_CD IN (2) THEN P.LAPTIME END AS LAPTIME_FP2,
            CASE WHEN P.SESSION_CD IN (2) THEN P.SECTOR1_TIME END AS SECTOR1_TIME_FP2,
            CASE WHEN P.SESSION_CD IN (2) THEN P.SECTOR2_TIME END AS SECTOR2_TIME_FP2,
            CASE WHEN P.SESSION_CD IN (2) THEN P.SECTOR3_TIME END AS SECTOR3_TIME_FP2,
            -- FP3
            CASE WHEN P.SESSION_CD IN (3) THEN P.LAPTIME END AS LAPTIME_FP3,
            CASE WHEN P.SESSION_CD IN (3) THEN P.SECTOR1_TIME END AS SECTOR1_TIME_FP3,
            CASE WHEN P.SESSION_CD IN (3) THEN P.SECTOR2_TIME END AS SECTOR2_TIME_FP3,
            CASE WHEN P.SESSION_CD IN (3) THEN P.SECTOR3_TIME END AS SECTOR3_TIME_FP3
        FROM SESSION.PRACTICE_RESULTS P
        WHERE DRIVER_ID NOT IN ('nan')
        ) P
    GROUP BY
        P.EVENT_CD,
        P.DRIVER_ID,
        P.TEAM_ID
)

SELECT
    P.EVENT_CD,
    P.DRIVER_ID,
    P.TEAM_ID,
    IFNULL(P.LAPTIME_FP1, 0) AS LAPTIME_FP1,
    IFNULL(P.SECTOR1_TIME_FP1, 0) AS SECTOR1_TIME_FP1,
    IFNULL(P.SECTOR2_TIME_FP1, 0) AS SECTOR2_TIME_FP1,
    IFNULL(P.SECTOR3_TIME_FP1, 0) AS SECTOR3_TIME_FP1,
    CASE WHEN P.LAPTIME_FP1 IS NULL THEN 1 ELSE 0 END AS FP1_MISSING,
    IFNULL(P.LAPTIME_FP2, 0) AS LAPTIME_FP2,
    IFNULL(P.SECTOR1_TIME_FP2, 0) AS SECTOR1_TIME_FP2,
    IFNULL(P.SECTOR2_TIME_FP2, 0) AS SECTOR2_TIME_FP2,
    IFNULL(P.SECTOR3_TIME_FP2, 0) AS SECTOR3_TIME_FP2,
    CASE WHEN P.LAPTIME_FP2 IS NULL THEN 1 ELSE 0 END AS FP2_MISSING,
    IFNULL(P.LAPTIME_FP3, 0) AS LAPTIME_FP3,
    IFNULL(P.SECTOR1_TIME_FP3, 0) AS SECTOR1_TIME_FP3,
    IFNULL(P.SECTOR2_TIME_FP3, 0) AS SECTOR2_TIME_FP3,
    IFNULL(P.SECTOR3_TIME_FP3, 0) AS SECTOR3_TIME_FP3,
    CASE WHEN P.LAPTIME_FP3 IS NULL THEN 1 ELSE 0 END AS FP2_MISSING,
    Q.Q_TIME
FROM SESSION_DAT P
LEFT JOIN QUALIFYING Q
    ON P.EVENT_CD = Q.EVENT_CD
    AND P.DRIVER_ID = Q.DRIVER_ID
WHERE
    Q.Q_TIME != 0