DROP TABLE IF EXISTS TABLEAU_DATA.ALL_SESSION_DATA;

CREATE TABLE TABLEAU_DATA.ALL_SESSION_DATA (
Driver VARCHAR(3),
DriverNumber INT,
Team VARCHAR(25),
LapTime FLOAT,
LapNumber INT,
Position INT,
Stint INT,
TyreLife INT,
FreshTyre INT,
Sector1Time FLOAT,
Sector2Time FLOAT,
Sector3Time FLOAT,
SpeedI1 FLOAT,
SpeedI2 FLOAT,
SpeedFL FLOAT,
SpeedST FLOAT,
IsPersonalBest BOOL,
Compound VARCHAR(20),
Deleted BOOL,
DeletedReason VARCHAR(50),
AirTemp FLOAT,
Rainfall BOOL,
TrackTemp FLOAT,
WindDirection FLOAT,
WindSpeed FLOAT,
TrackStatus INT,
IsAccurate BOOL,
Session VARCHAR(25),
event_name VARCHAR(50),
year INT,
event_type VARCHAR(25),
load_timestamp TIMESTAMP
)