SELECT
a.DRIVER,
a.DRIVER_NUMBER,
a.TEAM,
a.LAP_TIME,
a.LAP_NUMBER,
a.POSITION,
a.STINT,
a.TYRE_LIFE,
a.FRESH_TYRE,
a.SECTOR_1_TIME,
a.SECTOR_2_TIME,
a.SECTOR_3_TIME,
a.SPEED_I1,
a.SPEED_I2,
a.SPEED_FL,
a.SPEED_ST,
a.IS_PERSONAL_BEST,
a.COMPOUND,
a.DELETED,
a.DELETED_REASON,
a.AIR_TEMP,
a.RAINFALL,
a.TRACK_TEMP,
a.WIND_DIRECTION,
a.WIND_SPEED,
b.TRACK_STATUS,
a.IS_ACCURATE,
a.SESSION,
a.EVENT_NAME,
a.YEAR,
a.EVENT_TYPE
FROM
TABLEAU_DATA.ALL_SESSION_DATA a
LEFT JOIN TABLEAU_DATA.DIM_TRACK_STATUS b
ON a.TRACK_STATUS_CD = b.TRACK_STATUS_CD
WHERE
LAP_TIME is not NULL