DROP TABLE IF EXISTS SESSION.RACE_LAPS;

create table SESSION.RACE_LAPS (
    EVENT_CD INT(6),
    SESSION_CD INT(1),
    DRIVER_ID VARCHAR(30),
    TEAM_ID VARCHAR(30),
    LAPTIME FLOAT,
    LAP_NUMBER INT(2),
    PIT_IN_FLG INT(1),
    PIT_OUT_FLG INT(1),
    POSITION INT(2),
    STINT_NUMBER INT(2),
    SECTOR1_TIME FLOAT,
    SECTOR2_TIME FLOAT,
    SECTOR3_TIME FLOAT,
    SPEED_TRAP_1 INT(3),
    SPEED_TRAP_2 INT(3),
    SPEED_TRAP_FLAG INT(3),
    SPEED_TRAP_STRAIGHT INT(3),
    COMPOUND VARCHAR(50),
    TYRE_LIFE INT(3),
    LAP_START_DATETIME DATETIME,
    TRACK_STATUS INT(7),
    LAP_DELETED INT(1),
    LAP_DELETED_REASON VARCHAR(100),
    FF1_LAP_IS_ACCURATE INT(1),
    LOAD_TS DATETIME
)