DROP TABLE IF EXISTS WEATHER.WEATHER_FORECAST;

CREATE TABLE WEATHER.WEATHER_FORECAST (
FCST_LOCATION varchar(30),
FCST_DATETIME datetime,
TEMPERATURE float,
PRECIPITATION float,
PRECIPITATION_PROB float,
WIND_SPEED float,
WIND_DIRECTION float,
CLOUD_COVER float,
WEATHER_TYPE_CD float,
FCST_SOURCE varchar(30),
LOAD_TS datetime
);
