DROP TABLE IF EXISTS WEATHER.WEATHER_HISTORIC;

CREATE TABLE WEATHER.WEATHER_HISTORIC (
FCST_LOCATION varchar(30),
FCST_DATETIME datetime,
TEMPERATURE float,
PRECIPITATION float,
WIND_SPEED float,
WIND_DIRECTION float,
CLOUD_COVER float,
WEATHER_TYPE_CD float,
FCST_SOURCE varchar(20),
LOAD_TS datetime
);
