DROP TABLE IF EXISTS SESSION.QUALIFYING_RESULTS;

create table SESSION.QUALIFYING_RESULTS (
EVENT_CD INT(6),
SESSION_CD INT(1),
DRIVER_ID VARCHAR(30),
TEAM_ID VARCHAR(30),
Q_POSITION INT(2),
Q1_LAPTIME FLOAT,
Q2_LAPTIME FLOAT,
Q3_LAPTIME FLOAT,
Q_TIME FLOAT,
LOAD_TS DATETIME
)