DROP TABLE IF EXISTS SESSION.PRACTICE_RESULTS;

create table SESSION.PRACTICE_RESULTS (
EVENT_CD INT(6),
SESSION_CD INT(1),
DRIVER_ID VARCHAR(30),
TEAM_ID VARCHAR(30),
POSITION INT(2),
LAPTIME FLOAT,
SECTOR1_TIME FLOAT,
SECTOR2_TIME FLOAT,
SECTOR3_TIME FLOAT,
LOAD_TS DATETIME
)