DROP TABLE IF EXISTS SESSION.RACE_RESULTS;

create table SESSION.RACE_RESULTS (
EVENT_CD INT(6),
SESSION_CD INT(1),
DRIVER_ID VARCHAR(30),
TEAM_ID VARCHAR(30),
POSITION INT(2),
CLASSIFIED_POSITION VARCHAR(2),
TOTAL_TIME FLOAT,
DELTA FLOAT,
POINTS INT(2),
STATUS VARCHAR(15),
LOAD_TS DATETIME
)