CREATE OR REPLACE VIEW WEATHER.WEATHER_FORECAST_VW AS (
    WITH MAX_LOAD_TS AS (
        SELECT
            DISTINCT
            FCST_DATETIME,
            MAX(LOAD_TS) AS MAX_LTS
        FROM WEATHER.WEATHER_FORECAST
        GROUP BY
            FCST_DATETIME
    )

    SELECT
        FCST.*
    FROM WEATHER.WEATHER_FORECAST FCST
    INNER JOIN MAX_LOAD_TS LTS
        ON FCST.FCST_DATETIME = LTS.FCST_DATETIME
        AND FCST.LOAD_TS = LTS.MAX_LTS
)
