DROP VIEW IF EXISTS SESSION.CLEANED_PRACTICE_DATA;

CREATE VIEW SESSION.CLEANED_PRACTICE_DATA AS(
WITH session_data_temp AS (
    SELECT
        EVENT_CD,
        DRIVER_ID,
        TEAM_ID,
        CASE WHEN SESSION_CD IN (1) THEN POSITION END AS FP1_POSISTION,
        CASE WHEN SESSION_CD IN (1) THEN LAPTIME END AS FP1_LAPTIME,
        CASE WHEN SESSION_CD IN (1) THEN SECTOR1_TIME END AS FP1_SECTOR1_TIME,
        CASE WHEN SESSION_CD IN (1) THEN SECTOR2_TIME END AS FP1_SECTOR2_TIME,
        CASE WHEN SESSION_CD IN (1) THEN SECTOR3_TIME END AS FP1_SECTOR3_TIME,
        CASE WHEN SESSION_CD IN (2) THEN POSITION END AS FP2_POSISTION,
        CASE WHEN SESSION_CD IN (2) THEN LAPTIME END AS FP2_LAPTIME,
        CASE WHEN SESSION_CD IN (2) THEN SECTOR1_TIME END AS FP2_SECTOR1_TIME,
        CASE WHEN SESSION_CD IN (2) THEN SECTOR2_TIME END AS FP2_SECTOR2_TIME,
        CASE WHEN SESSION_CD IN (2) THEN SECTOR3_TIME END AS FP2_SECTOR3_TIME,
        CASE WHEN SESSION_CD IN (3) THEN POSITION END AS FP3_POSISTION,
        CASE WHEN SESSION_CD IN (3) THEN LAPTIME END AS FP3_LAPTIME,
        CASE WHEN SESSION_CD IN (3) THEN SECTOR1_TIME END AS FP3_SECTOR1_TIME,
        CASE WHEN SESSION_CD IN (3) THEN SECTOR2_TIME END AS FP3_SECTOR2_TIME,
        CASE WHEN SESSION_CD IN (3) THEN SECTOR3_TIME END AS FP3_SECTOR3_TIME
    FROM SESSION.PRACTICE_RESULTS
    WHERE DRIVER_ID != 'nan'

)

SELECT
    EVENT_CD,
    DRIVER_ID,
    TEAM_ID,
    ROUND(SUM(FP1_POSISTION), 3) AS FP1_POSISTION,
    ROUND(SUM(FP1_LAPTIME), 3) AS FP1_LAPTIME,
    ROUND(SUM(FP1_SECTOR1_TIME), 3) AS FP1_SECTOR1_TIME,
    ROUND(SUM(FP1_SECTOR2_TIME), 3) AS FP1_SECTOR2_TIME,
    ROUND(SUM(FP1_SECTOR3_TIME), 3) AS FP1_SECTOR3_TIME,
    ROUND(SUM(FP2_POSISTION), 3) AS FP2_POSISTION,
    ROUND(SUM(FP2_LAPTIME), 3) AS FP2_LAPTIME,
    ROUND(SUM(FP2_SECTOR1_TIME), 3) AS FP2_SECTOR1_TIME,
    ROUND(SUM(FP2_SECTOR2_TIME), 3) AS FP2_SECTOR2_TIME,
    ROUND(SUM(FP2_SECTOR3_TIME), 3) AS FP2_SECTOR3_TIME,
    ROUND(SUM(FP3_POSISTION), 3) AS FP3_POSISTION,
    ROUND(SUM(FP3_LAPTIME), 3) AS FP3_LAPTIME,
    ROUND(SUM(FP3_SECTOR1_TIME), 3) AS FP3_SECTOR1_TIME,
    ROUND(SUM(FP3_SECTOR2_TIME), 3) AS FP3_SECTOR2_TIME,
    ROUND(SUM(FP3_SECTOR3_TIME), 3) AS FP3_SECTOR3_TIME
FROM session_data_temp
GROUP BY
    EVENT_CD,
    DRIVER_ID,
    TEAM_ID
)