DROP TABLE IF EXISTS REFERENCE.DIM_DRIVER;

create table REFERENCE.DIM_DRIVER (
DRIVER_ID VARCHAR(50),
DRIVER_NUMBER INT(2),
DRIVER_CODE VARCHAR(3),
DRIVER_URL VARCHAR(100),
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
DATE_OF_BIRTH DATE,
NATIONALITY VARCHAR(50),
LOAD_TS DATETIME
)