DROP TABLE IF EXISTS REFERENCE.DIM_CONSTRUCTOR;

create table REFERENCE.DIM_CONSTRUCTOR (
CONSTRUCTOR_ID VARCHAR(50),
CONSTRUCTOR_URL VARCHAR(100),
NAME VARCHAR(50),
NATIONALITY VARCHAR(50),
LOAD_TS DATETIME
)