DROP TABLE IF EXISTS REFERENCE.DIM_SESSION;

create table REFERENCE.DIM_SESSION (
SESSION_CD INT(1),
SESSION_NAME VARCHAR(25),
SESSION_SRT_NAME VARCHAR(10),
SESSION_GROUP_NAME VARCHAR(25),
SESSION_GROUP_SRT_NAME VARCHAR(10),
LOAD_TS DATETIME
)