DROP TABLE IF EXISTS REFERENCE.DIM_TRACK;

CREATE TABLE REFERENCE.DIM_TRACK (
TRACK_CD int,
TRACK_ID varchar(50),
TRACK_NAME varchar(50),
LOCATION varchar(50),
COUNTRY varchar(50),
LATITUDE float,
LONGITUDE float,
TRACTION int,
TYRE_STRESS int,
ASPHALT_GRIP int,
BRAKING int,
ASPHALT_ABRASION int,
LATERAL_FORCE int,
TRACK_EVOLUTION int,
DOWNFORCE int
)