DROP TABLE IF EXISTS DIM_TRACK;

CREATE TABLE DIM_TRACK (
TRACK_CD int,
TRACK_NAME varchar(50),
LOCATION varchar(50),
TRACTION int,
TYRE_STRESS int,
ASPHALT_GRIP int,
BRAKING int,
ASPHALT_ABRASION int,
LATERAL_FORCE int,
TRACK_EVOLUTION int,
DOWNFORCE int,
LOAD_TS DATETIME
)