DROP TABLE IF EXISTS ML_PROJECT_PROD.WEATHER_FORECAST;

CREATE TABLE ML_PROJECT_PROD.WEATHER_FORECAST (
FCST_LOCATION varchar(30),
FCST_DATETIME datetime,
TEMPERATURE float,
PRECIPITATION float,
PRECIPITATION_PROB float,
WIND_SPEED float,
WIND_DIRECTION float,
CLOUD_COVER float,
CONDITIONS varchar(30),
FCST_SOURCE varchar(20),
LOAD_TS datetime
);
