DROP TABLE IF EXISTS weather_forcast;

CREATE TABLE WEATHER_FORECAST (
FCST_LOCATION varchar(30),
FCST_DATETIME datetime,
TEMPERATURE float,
PERCIPITATION float,
PERCIPITATION_PROB float,
WIND_SPEED float,
WIND_DIRECTION float,
CLOUD_COVER float,
CONDITIONS varchar(30),
FCST_SOURCE varchar(5),
LOAD_TS datetime
)
