DROP TABLE IF EXISTS raw_session_data;

CREATE TABLE raw_session_data (
DriverNumber int,
LapTimeFP1 float,
Sector1TimeFP1 float,
Sector2TimeFP1 float,
Sector3TimeFP1 float,
CompoundFP1 varchar(20),
AirTempFP1 float,
RainfallFP1 varchar(10),
TrackTempFP1 float,
WindDirectionFP1 int,
WindSpeedFP1 float,
LapTimeFP2 float,
Sector1TimeFP2 float,
Sector2TimeFP2 float,
Sector3TimeFP2 float,
CompoundFP2 varchar(20),
AirTempFP2 float,
RainfallFP2 varchar(10),
TrackTempFP2 float,
WindDirectionFP2 int,
WindSpeedFP2 float,
LapTimeFP3 float,
Sector1TimeFP3 float,
Sector2TimeFP3 float,
Sector3TimeFP3 float,
CompoundFP3 varchar(20),
AirTempFP3 float,
RainfallFP3 varchar(10),
TrackTempFP3 float,
WindDirectionFP3 int,
WindSpeedFP3 float,
LapTimeQ float,
Sector1TimeQ float,
Sector2TimeQ float,
Sector3TimeQ float,
CompoundQ varchar(20),
AirTempQ float,
RainfallQ varchar(10),
TrackTempQ float,
WindDirectionQ int,
WindSpeedQ float,
event_name varchar(50),
year int,
event_type varchar(20)
)